vich_uploader:
  db_driver: orm

  metadata:
    type: attribute

  mappings:
    poster_file:
      uri_prefix: '%app.path.posters_images%'
      upload_destination: '%kernel.project_dir%/public%app.path.posters_images%'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
